### ISSUE TITLE
Daily Challenge Unlimited button doesn't fade when ending a game immediately

### ISSUE THREAD

**Issue by kuglee** [pointfreeco/isowords#42]
I've started the Daily Unlimited challenge and then ended it without doing anything. Now the game doesn't let me play the challenge again which is fine, but the button isn't faded out.

<table>
  <tr>
    <td>
      <img src="https://user-images.githubusercontent.com/1316211/112306288-f1d6b180-8c9f-11eb-93b5-f16feb7f9c44.PNG">
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/1316211/112306294-f4390b80-8c9f-11eb-85a4-1b3608b433b5.PNG">
    </td>
  </tr>
</table>

**Comment by stephencelis** [comment]
Hi @kuglee. This is by design. Once you end a daily challenge you can't start another one till the next day. You can always save your unlimited progress by tapping "Main menu" instead of "End game." We'll try to think of ways of handling edge cases like yours, and maybe how we can be more forgiving of this kind of thing in the future, though!

**Comment by kuglee** [comment]
I see. Thanks.
